plugins {
    id 'ramus.java-conventions'
}

dependencies {
    implementation project(':data-framework-common')
    implementation project(':database-storage')
    implementation project(':common')
    implementation project(':core')
    implementation project(':core-simple-attributes')
    implementation 'net.htmlparser.jericho:jericho-html:3.3'
    testImplementation 'junit:junit:4.13.2'
}
