plugins {
    id 'ramus.java-conventions'
}

dependencies {
    implementation project(':idef0-common')
    implementation project(':idef0-core')
    implementation project(':idef0-report-core')
    implementation project(':local-client')
    implementation project(':gui-framework-common')
    implementation project(':common')
    implementation project(':data-framework-common')
    implementation project(':core')
    testImplementation 'junit:junit:4.13.2'
}
