plugins {
    id 'ramus.java-conventions'
}

dependencies {

    implementation project(':common')
    implementation project(':core-simple-attributes')
    implementation project(':data-framework-common')
    implementation project(':gui-framework-common')
    implementation 'org.swinglabs.swingx:swingx-all:1.6.5-1'
    implementation 'net.htmlparser.jericho:jericho-html:3.4'
    implementation project(':report-core')
    implementation project(':gui-qualifier')
    implementation 'de.sciss:jsyntaxpane:1.0.0'
    testImplementation 'junit:junit:4.13.2'
}
